### ISSUE TITLE
sensorId issue

### ISSUE THREAD

**Issue by simchanewman** [aliceliveprojects/pi_scalextric_mqtt#2]
Currently, while using MQTT box when a car passes the sensorId's 1,2,3,4 do not pick up a publish event when subscribed with MQTTbox. In our project, we would like to be able to access the sensorId to allow us to add certain features to our application.

**Comment by coopsatwork** [comment]
hi @simchanewman, thanks for the note - seems like some other users are setting the trigger values on MQTT, while they're working on it. When we reboot the Pi, it publishes the original values, and the sensors work fine again. 
Closing the issue, but get back to us in any more probs :-)
